### ISSUE TITLE
qGIS 3.0 Girona

### ISSUE THREAD

**Issue by aourednik** [zsiki/realcentroid#9]
This is a great plugin. Would you agree to update it to work in qGIS 3.0 Girona ?
Trying to install from zip triggers the following error: 

`Couldn't load plugin 'realcentroid' due to an error when calling its classFactory() method 

ImportError: cannot import name 'RealCentroid' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/a/.local/share/QGIS/QGIS3/profiles/default/python/plugins/realcentroid/__init__.py", line 26, in classFactory
    from realcentroid import RealCentroid
ImportError: cannot import name 'RealCentroid'

Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] 
QGIS version: 3.0.2-Girona Girona, 307d082 `

**Comment by zsiki** [comment]
Point on surface has been added to processing algorithms in QGIS 3. See QGIS Vector Geometry/Point on Surface. It has the same functionality as Realcentroid, except the default output format is GeoPackage.

**Comment by aourednik** [comment]
It works indeed. Many thanks for your answer. 

Testing it, Geometry/Point on Surface works very well here

![point_on_surface](https://user-images.githubusercontent.com/7204421/39477952-2372b238-4d61-11e8-953f-65397d9ad037.png)

Less well here, though the point remains inside of the polygon:

![point_on_surface2](https://user-images.githubusercontent.com/7204421/39477961-2eff84aa-4d61-11e8-82e1-741844bfb2ab.png)

Is Geometry/Point on Surface using the same algorithm as realcentroids?

**Comment by zsiki** [comment]
Above QGIS 2.4 Realcentroid calls GEOS PointOnSurface function and processing in QGIS 3, too.
